#!/usr/bin/env python
"""Round 1 of v6/plan0.md: the new qx,qy terms in starlib.project/solve_plate on their own.

No images, no real star catalog, no GPU, ~1 s. Plants a full synthetic plate solution --
affine + rotation + parity + k1/k2 lens distortion + the new qx,qy separable atmosphere
terms -- generates "detected" star pixel positions from it via the exact same `project()`
the solver uses, then asserts `solve_plate(..., use_atmosphere=True)` recovers it. Same
shape as v5/test_calib_synthetic.py: plant a known truth, assert the solver finds it.

This only proves the mechanism works when the data really was generated by this model and
is plentiful and noiseless. It says nothing about whether ~20-25 real, imperfectly placed
stars can constrain qx,qy without being degenerate with k1,k2 -- that is round 2
(find_stars/check_11_atmosphere_warp.py), against the real 2024 anchors.

Run directly (`python v6/test_warp_terms.py`) or under pytest.
"""
from __future__ import annotations

import math
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "find_stars"))

import starlib as S  # noqa: E402

SEED = 20260812
N_STARS = 60

# A plausible-ish 2026 plate: real scale/frame size, arbitrary but non-trivial pointing,
# rotation, parity and distortion so no axis or sign is accidentally untested.
RA0, DEC0 = 142.105, 14.907
SCALE0 = 3.061          # "/px, Z6 400mm
CX0, CY0 = 3024.0, 2012.0
ROT_TRUE = 15.0
PARITY_TRUE = 1
K1_TRUE, K2_TRUE = 0.02, -0.01
QX_TRUE, QY_TRUE = 20.0, -15.0


def make_truth(seed=SEED):
    rng = np.random.default_rng(seed)
    dec = DEC0 + rng.uniform(-1.7, 1.7, N_STARS)
    ra = RA0 + rng.uniform(-2.6, 2.6, N_STARS) / math.cos(math.radians(DEC0))
    p_true = np.concatenate([
        S.affine_from(SCALE0, ROT_TRUE, PARITY_TRUE, CX0, CY0),
        [K1_TRUE, K2_TRUE, QX_TRUE, QY_TRUE],
    ])
    xi, eta = S.gnomonic(ra, dec, RA0, DEC0)
    det_x, det_y = S.project(p_true, xi, eta)
    return ra, dec, det_x, det_y, p_true


def test_atmosphere_terms_recovered_from_synthetic_stars():
    ra, dec, det_x, det_y, p_true = make_truth()

    res = S.solve_plate(det_x, det_y, ra, dec, RA0, DEC0, CX0, CY0, SCALE0,
                        use_distortion=True, use_atmosphere=True, rot_step=0.5)
    p = res["p"]

    print(f"brute force: rot={res['brute_rot']:.2f} parity={res['brute_parity']} "
          f"n={res['brute_n']}/{N_STARS}")
    print(f"matched {res['nmatch']}/{N_STARS}, rms {res['rms']:.4f} px")
    print(f"  k1  true {K1_TRUE:+.4f}  recovered {p[6]:+.4f}")
    print(f"  k2  true {K2_TRUE:+.4f}  recovered {p[7]:+.4f}")
    print(f"  qx  true {QX_TRUE:+.4f}  recovered {p[8]:+.4f}")
    print(f"  qy  true {QY_TRUE:+.4f}  recovered {p[9]:+.4f}")

    assert res["nmatch"] == N_STARS, res["nmatch"]
    assert res["rms"] < 0.01, res["rms"]
    assert abs(p[8] - QX_TRUE) < 0.05, (p[8], QX_TRUE)
    assert abs(p[9] - QY_TRUE) < 0.05, (p[9], QY_TRUE)

    # Held-out check: a grid of xi,eta never used in the fit, well off the fitted stars.
    # This is the claim that actually matters -- the *map*, not the individual coefficients
    # (plan0.md's "the degeneracy that doesn't need resolving" argues coefficients alone can
    # be unstable on real data; the map is what gets applied to a frame).
    gv, gt = np.meshgrid(np.linspace(-2.2, 2.2, 15), np.linspace(-1.4, 1.4, 15))
    ra_g = RA0 + gv.ravel() / math.cos(math.radians(DEC0))
    dec_g = DEC0 + gt.ravel()
    xi_g, eta_g = S.gnomonic(ra_g, dec_g, RA0, DEC0)
    x_true, y_true = S.project(p_true, xi_g, eta_g)
    x_fit, y_fit = S.project(p, xi_g, eta_g)
    err = np.hypot(x_fit - x_true, y_fit - y_true)
    print(f"held-out grid: max {err.max():.4f} px, mean {err.mean():.4f} px")
    assert err.max() < 0.05, err.max()


def test_zero_atmosphere_terms_is_pure_distortion():
    """qx=qy=0 must reproduce plain k1/k2 exactly -- the new branch must not leak."""
    p8 = np.concatenate([S.affine_from(SCALE0, ROT_TRUE, PARITY_TRUE, CX0, CY0),
                         [K1_TRUE, K2_TRUE]])
    p10 = np.concatenate([p8, [0.0, 0.0]])
    xi = np.linspace(-3000.0, 3000.0, 50)
    eta = np.linspace(-2000.0, 2000.0, 50)
    x8, y8 = S.project(p8, xi, eta)
    x10, y10 = S.project(p10, xi, eta)
    assert np.allclose(x8, x10) and np.allclose(y8, y10)


if __name__ == "__main__":
    test_atmosphere_terms_recovered_from_synthetic_stars()
    test_zero_atmosphere_terms_is_pure_distortion()
    print("OK")
